"""
Report Generator Module
Produces a structured analyst-style report from agent findings.
"""

from datetime import datetime

def generate_report(ticker: str, company: str, news_items: list,
                   sentiment_results: list, signal: dict) -> str:
    """
    Generates a structured analyst report.
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    breakdown = signal['breakdown']

    # Top headlines
    top_positive = [r for r in sentiment_results if r['label'] == 'POSITIVE'][:2]
    top_negative = [r for r in sentiment_results if r['label'] == 'NEGATIVE'][:2]

    report = f"""
╔══════════════════════════════════════════════════════╗
║           FINSIGHT AI — ANALYST REPORT               ║
╚══════════════════════════════════════════════════════╝

Stock    : {ticker}
Company  : {company}
Date     : {now}
Articles : {breakdown['total']} analyzed

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SIGNAL: {signal['recommendation']}
Confidence: {signal['confidence']}%
Reasoning : {signal['reasoning']}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SENTIMENT BREAKDOWN
  Positive : {breakdown['positive']} articles
  Neutral  : {breakdown['neutral']} articles
  Negative : {breakdown['negative']} articles

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

TOP POSITIVE SIGNALS"""

    if top_positive:
        for r in top_positive:
            report += f"\n  ✅ [{r['score']:+.2f}] {r['title'][:70]}"
    else:
        report += "\n  None found"

    report += "\n\nTOP NEGATIVE SIGNALS"
    if top_negative:
        for r in top_negative:
            report += f"\n  ❌ [{r['score']:+.2f}] {r['title'][:70]}"
    else:
        report += "\n  None found"

    report += f"""

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

⚠️  DISCLAIMER
This report is generated by an AI agent for educational 
purposes only. Not financial advice. Always do your own 
research before making investment decisions.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by FinSight Agent | github.com/minshhh4
"""
    return report
